### ISSUE TITLE
Compatability issue?

### ISSUE THREAD

**Issue by SnowHana** [opennem/opennem#336]
usr/local/bin/python3 /Users/nautilus/scif3000/scif3000/practice.py                                                                                                                        ─╯

Traceback (most recent call last):
  File "/Users/nautilus/scif3000/scif3000/practice.py", line 1, in <module>
    import opennem as on
  File "/usr/local/lib/python3.11/site-packages/opennem/__init__.py", line 24, in <module>
    from .client import OpenNEMClient  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/opennem/client.py", line 14, in <module>
    from opennem.utils.http import http
  File "/usr/local/lib/python3.11/site-packages/opennem/utils/http.py", line 55, in <module>
    retry_strategy = Retry(
                     ^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'

Uhm i have no idea what's going on

**Comment by nc9** [comment]
hi @SnowHana - the python client has been a bit neglected because we're under-resourced. We have a plan to allocate more time to it and open it to contributors (it's just OpenAPI, afterall)

I'll see if I can dig in and find your exact issue, I might need a bit more context of what you're running

/cc @gmmspi

**Comment by SnowHana** [comment]
Yep. I'm running on intel mac os, under a venv.
Below is installed packages
Thank you!
<img width="187" alt="Screenshot 2023-09-26 at 1 51 42 pm" src="https://github.com/opennem/opennem/assets/66943395/e51e8194-ceb6-4544-b2be-58ab1b8c01de">

**Comment by nc9** [comment]
@SnowHana Try using poetry to install, we have a wiki page on it:

https://github.com/opennem/opennem/wiki/Backend-Install-and-Setup

we've moved on to the `pyproject.toml` standard since day 1 of the project and only had requirements.txt for backwards-compat, but recently stopped updating that as well

Let me know how you get along

**Comment by nc9** [comment]
closing, stale support question from an old release, no follow up
